title: Matt Campbell
email: matthewcampbell508@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My personal site containing ramblings as a professional web developer. I mainly work with backend like PHP (Laravel)
  and I have also have frontend experience.

  I have a passion for trying to share knowledge.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mcampbell508.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mcampbell508
github_username:  mcampbell508

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - Gemfile
    - Gemfile.lock
