#
# This file contains configuration flags to customize your site
#

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:           pretty

excerpt_separator: '<br>'

# Setup
title: Matt Campbell
email: matthewcampbell508@gmail.com
description: >-
  My personal site containing ramblings as a software developer. I mainly work with backend development with PHP (Laravel)
  and I have also have some DevOps experience with tools like Ansible, Terraform and Kubernetes. I have a passion for trying to share knowledge.
baseurl: '/'
url: "https://mcampbell508.github.io"
twitter_username: mcampbell508
github_username:  mcampbell508
paginate: 5

author:
  name: 'Matt Campbell'
  github: mcampbell508

# Custom vars
version: 1.0.0
github:
  repo: https://github.com/mcampbell508/mcampbell508.github.io

curriculum_vitae: https://github.com/mcampbell508/mcampbell508.github.io/blob/master/_site/resume.pdf

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - resume

plugins:
  - jekyll-feed
